apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-api
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@github.com/TlStephen2011/test-api-infrastructure.git
  secretRef:
    name: flux-system
  ref:
    branch: main