apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: test-api-image-automation
  namespace: test
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: test-api
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux-cd-automation@noreply.com
        name: flux-cd
      messageTemplate: 'Update image to "{{ .ImagePolicy.Name }}:{{ .ImagePolicy.LatestImage }}"'
    push:
      branch: main
  update:
    path: ./test-api